defaults: &defaults
  aucfan:
    name: "株式会社オークファン"
    address: "東京都品川区大崎..."
    service:
      guide: "タテンポガイド"
      robo: "オークファンロボ"
      pro: "aucfan Pro."

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults